import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const data = await req.json();
    
    // Validate we have data
    if (!data) {
      return NextResponse.json({ error: 'No data provided' }, { status: 400 });
    }

    // You will need an App Password if using Gmail
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER || 'info.labgraphics@gmail.com',
        pass: process.env.GMAIL_APP_PASSWORD, // Add this to .env.local
      },
    });

    // Format the email
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h2 style="color: #4A151B; border-bottom: 2px solid #4A151B; padding-bottom: 10px;">New Lab Graphics Intake Lead!</h2>
        
        <h3 style="color: #999999;">1. Contact Details</h3>
        <p><strong>Name:</strong> ${data.fullName || 'N/A'}</p>
        <p><strong>Email:</strong> ${data.email || 'N/A'}</p>
        <p><strong>Phone:</strong> ${data.phone || 'N/A'}</p>
        <p><strong>Preferred Contact Method:</strong> ${data.contactPreference || 'N/A'}</p>
        <p><strong>Preferred Call Time:</strong> ${data.preferredDate || 'N/A'} at ${data.preferredTime || 'N/A'}</p>

        <h3 style="color: #999999;">2. Business & Scope</h3>
        <p><strong>Business Name:</strong> ${data.businessName || 'N/A'}</p>
        <p><strong>Description:</strong> ${data.businessDescription || 'N/A'}</p>
        <p><strong>Current Website:</strong> ${data.currentWebsite || 'N/A'}</p>
        <p><strong>Primary Goal:</strong> ${data.primaryGoal || 'N/A'}</p>
        <p><strong>Target Audience:</strong> ${data.targetAudience || 'N/A'}</p>
        <p><strong>Budget Range:</strong> <span style="font-weight: bold; color: #4A151B;">${data.budgetRange || 'N/A'}</span></p>

        <h3 style="color: #999999;">3. Requirements (Checklists)</h3>
        <p><strong>Content Readiness:</strong> ${data.contentStatus || 'N/A'}</p>
        <p><strong>Pages Needed:</strong> ${data.pages?.length ? data.pages.join(', ') : 'None'}</p>
        <p><strong>Features Needed:</strong> ${data.features?.length ? data.features.join(', ') : 'None'}</p>

        <h3 style="color: #999999;">4. Technical & Extras</h3>
        <p><strong>Logo Status:</strong> ${data.hasLogo || 'N/A'}</p>
        <p><strong>Hosting Provider:</strong> ${data.hostingProvider || 'N/A'}</p>
        <p><strong>Color Preference:</strong> ${data.colorPreference || 'N/A'}</p>
        <p><strong>Font Preference:</strong> ${data.fontPreference || 'N/A'}</p>
        <p><strong>Additional Services:</strong> ${data.serviceAddons?.length ? data.serviceAddons.join(', ') : 'None'}</p>

        <br/>
        <p style="font-size: 12px; color: #999999;">This lead was securely generated by your Next.js Intake Application.</p>
      </div>
    `;

    // Only attempt to send if credentials are provided to prevent crash on demo
    if (process.env.GMAIL_APP_PASSWORD) {
      await transporter.sendMail({
        from: process.env.GMAIL_USER || 'info.labgraphics@gmail.com',
        to: 'info.labgraphics@gmail.com',
        subject: `New Lead: ${data.fullName || 'Unknown'} - ${data.businessName || 'Business'}`,
        html: htmlContent,
      });
    } else {
      console.warn("EMAIL_PASS not found in environment variables. Email was not sent to SMTP server, but API returned success for UI testing.");
      console.log("Captured Data:", JSON.stringify(data, null, 2));
    }

    return NextResponse.json({ success: true, message: 'Lead submitted successfully' });
  } catch (error) {
    console.error('Error submitting form:', error);
    return NextResponse.json({ error: 'Failed to submit form' }, { status: 500 });
  }
}
